### ISSUE TITLE
Not possible to uninstall Actions permissions (VBO)

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/views_bulk_operations#25] opened 2022-11-20 21:48 UTC
While uninstalling this submodule the following error occurs (dblog):

`Error: Call to undefined function views_bulk_operations_actions_get_info() in actions_permissions_permission() (line 8 of /mypath/modules/views_bulk_operations/modules/actions_permissions.module).`

**Comment by argiepiano** [comment] 2022-11-21 22:41
Thanks for reporting! Unlike the D7 version of VBO, Actions permissions must depend on VBO in Backdrop. A solution for your case is to:
1. Re-enable Views Bulk Operations
2. Disable Actions Permissions
3. Disable VBO

I'll make a PR for a new version of VBO that incorporates this dependency in the near future.

**Comment by argiepiano** [comment] 2022-11-21 22:49
If you can't re-enable VBO (for example if your site is not working because of the error), you may need to disable Actions Permissions by editing the system table in the database, as a last resort.

**Comment by djzwerg** [comment] 2022-11-21 23:06
> Thanks for reporting! Unlike the D7 version of VBO, Actions permissions must depend on VBO in Backdrop. A solution for your case is to:
> 1. Re-enable Views Bulk Operations
> 2. Disable Actions Permissions
> 3. Disable VBO
> 
> I'll make a PR for a new version of VBO that incorporates this dependency in the near future.

I've tried this, too. After the error page both modules seem to be uninstalled but after re-installing there is the same behavior on uninstall.

**Comment by argiepiano** [comment] 2022-11-22 00:43
> After the error page both modules seem to be uninstalled but after re-installing there is the same behavior on uninstall.

This is strange. I just can't reproduce this with the information you have provided. The only way for me to reproduce it is by disabling VBO and keeping Actions permissions, and then clearing the cache - then I get the error. Perhaps I'm not understanding what's causing this, or there is a step missing in your description, or your installation has other problems. Is this a development site? You may want to restore your last backup and restart the installation etc.

IF both modules are enabled and installed, tried fully uninstalling Actions permissions FIRST. Then uninstall VBO.

Also, a clarification: the PR I provided here has not yet been merged, and is not part of the dev version nor of any version of VBO. However, the steps I mentioned (being sure both modules are installed, and are present in the correct directory, uninstalling Actions permissions first, then VBO) should work without the patch.

**Closed as completed** 2023-10-03 02:02 UTC
